### ISSUE TITLE
SyntaxError: Unexpected token *

### ISSUE THREAD

**Issue by egr7v8** [PocketNode/PocketNode#17]
```
/home/egr7v8/PocketNode/src/pocketnode/math/Vector3.js:188
        return ((this.x - pos.x) ** 2) + ((this.y - pos.y) ** 2) + ((this.z - pos.z) ** 2);
                                  ^

SyntaxError: Unexpected token *
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at global.pocketnode (/home/egr7v8/PocketNode/src/pocketnode/utils/methods/Globals.js:9:12)
```

**Comment by hcortezr** [comment]
update to the latest node.js
