### ISSUE TITLE
Can't start the server

### ISSUE THREAD

**Issue by Gabitzuu** [PocketNode/PocketNode#2]
I can't start the server because i get this error:

```module.js:515
    throw err;
    ^

Error: Cannot find module './OfflineMessageHandler'
    at Function.Module._resolveFilename (module.js:513:15)
    at Function.Module._load (module.js:463:25)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Gabitzuu\Desktop\PocketNode\PocketNode\src\raknet\server\SessionManager.js:2:31)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
```

What can i do?

**Comment by Gabitzuu** [comment]
nvm, i resolved it, and i will make a pull request with the fix.
